spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  base-url: http://localhost:8080